### ISSUE TITLE
The Arrow class is redundant

### ISSUE THREAD

**Issue by ekmett** [purescript/purescript-arrows#9]
An `Arrow` isn't a `Strong` `Category` with extra stuff, it is [precisely](http://www.fceia.unr.edu.ar/~mauro/pubs/Notions_of_Computation_as_Monoids.pdf) `Strong` + `Category`.

There isn't anything gained by having a separate class except now a risk that someone might have a constraint that requires it and which isn't satisfied by the logically equivalent pair of `Strong` and `Category` constraints.

If the purescript equivalent of `UndecidableInstances` works correctly here you could just make one instance for `Arrow` and call it good as a shorthand.

**Comment by paf31** [comment]
Yes, this library has been shrinking ever since `purescript-profunctors` came into existence. Now that we have `Star`, it probably makes sense to add `Costar`, deprecate (`Co`)`Kleisli` and move `Static` out.

Are there `Profunctor` versions of `ArrowZero` and `ArrowPlus`? (Not that we currently use them anywhere...)

**Comment by paf31** [comment]
Or, yes, the `UndecidableInstances` approach should work too.

**Comment by ekmett** [comment]
`ArrowZero` is a 'unit first' sort of definition, as such I tend to avoid defining things that way. I've found it tends to be less useful than I'd want. Mathematicians don't like writing down a unit then looking for operations that work with that unit. With `Arrow` underneath it at least has the multiplicative structure to be cancellative for, though.

Modulo superclasses `ArrowPlus` (without `ArrowZero`) is basically a sum-based variant of the `both` based `Wander` type.

This gets pretty granular if you let it. ;)
